---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Install htop
    package:
      name: 
        - htop
        - tmux
  
  - name: Install Snap package of Spotify
    snap:
      name: spotify
      state: present
