---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Install htop
    package:
      name: 
        - htop
        - tmux
  
          #- name: Install Snap package of Spotify
          #community.general.snap:
          #name: spotify
