---
- hosts: all                                                                                                                                                                                                     
  remote_user: ansible                                                                                                                                                                                           
  become: yes                                                                                                                                                                                                    
  gather_facts: yes 
  roles:
    - zsh
    - timezone
