---
# tasks file for zsh

- name: Install Zsh on computer
  package: 
    name: zsh
    state: latest


      #- name: Download zsh zip file
      #get_url:
      #url: http://192.168.1.134/zsh.tgz 
      #dest: /tmp/zsh.tgz 
      #owner: nash
      # group: nash


- name: Install oh-my-zsh
  shell: /usr/bin/sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"


- name: Install zplug
  shell: curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
  ignore_errors: yes


    #- name: Untar zsh.tgz
    #unarchive:
    # src: /tmp/zsh.tgz
    # dest: /home/nash/
